Missing BR for tests
+ /usr/bin/python2 setup.py test
running test
Searching for mock>=2.0
...
No local packages or download links found for mock>=2.0
error: Could not find suitable distribution for Requirement.parse('mock>=2.0')